[workspace]
default-members = [ "smplx" ]

exclude = [  ]

members = [ "smplx" ]

resolver = "3"

[workspace.package]
authors = [
    "Joe McCain III <jo3mccain@icloud.com>",
]
categories = [ "mathematics" ]
description = "smplx focuses on the simplex and its applications in mathematics, topology, and other fields."
edition = "2024"
homepage = "https://github.com/FL03/smplx/wiki"
keywords = [
    "mathematics",
    "simplex",
    "topology",
]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/FL03/smplx.git"
version = "0.0.2"

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = 'unwind'
rpath = false

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = false
panic = 'abort'
rpath = false
