[package]
build = "build.rs"
name = "smplx"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [ "std" ]

full = [
    "approx",
    "default",
    "serde",
]

# ********* [FF] Dependencies *********
alloc = [
    "num/alloc",
    "nalgebra?/alloc",
    "serde?/alloc",
]

approx = [
    "dep:approx",
    "ndarray?/approx",
]

blas = [
    "ndarray?/blas",
    "ndarray-linalg?/blas",
]

nalgebra = [
    "dep:nalgebra",
]

ndarray = [
    "dep:ndarray",
    "dep:ndarray-linalg",
]

rayon = [
    "nalgebra?/rayon",
    "ndarray?/rayon",
]

serde = [
    "dep:serde",
    "nalgebra?/serde",
    "ndarray?/serde",
    "serde?/derive",
]

# ********* [FF] Environments *********
std = [
    "alloc",
    "approx?/std","nalgebra?/std",

    "ndarray?/std",
    "num/std",
    "serde?/std",
]

# ********* [FF] blas *********
intel-mkl = [
    "blas",
    "ndarray-linalg?/intel-mkl",
]

intel-mkl-static = [
    "blas",
    "ndarray-linalg?/intel-mkl-static",
]

intel-mkl-system = [
    "blas",
    "ndarray-linalg?/intel-mkl-system",
]

openblas = [
    "blas",
    "ndarray-linalg?/openblas",
]

openblas-system = [
    "blas",
    "ndarray-linalg/openblas-system",
]

openblas-static = [
    "blas",
    "ndarray-linalg?/openblas-static",
]

netlib = [
    "blas",
    "ndarray-linalg?/netlib",
]

netlib-static = [
    "blas",
    "ndarray-linalg?/netlib-static",
]

netlib-system = [
    "blas",
    "ndarray-linalg?/netlib-system",
]

[lib]
bench = true
crate-type = [
    "cdylib",
    "rlib",
]
doctest = false
test = true

[[test]]
name = "quick_hull"
required-features = ["approx", "ndarray", "std"]
[[test]]
name = "ndsimplex"
required-features = [
    "approx",
    "blas",
    "ndarray",
    "std",
]

[dependencies]
approx = { default-features = false, optional = true, version = "0.5" }
nalgebra = { default-features = false, optional = true, version = "0.33" }
ndarray = { default-features = false, optional = true, version = "0.16" }
ndarray-linalg = { default-features = false, optional = true, version = "0.17" }
num = { default-features = false, version = "0.4" }
serde = { default-features = false, optional = true, version = "1" }
strum = { default-features = false, features = [
    "derive",
], version = "0.27" }
thiserror = { default-features = false, version = "2" }

[dev-dependencies]
anyhow = "1"
approx = "0.5"
lazy_static = "1"

[package.metadata.docs.rs]
all-features = true
rustc-args = [
    "--cfg",
    "docsrs",
]
