[package]
authors.workspace = true
build = "build.rs"
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "smplx"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "std",
]

full = [
    "default",
    "serde",
]

# ********* [FF] Dependencies *********
alloc = [
    "nalgebra/alloc",
    "serde?/alloc",
]

serde = [
    "dep:serde",
    "nalgebra/serde",
    "serde?/derive"
]

# ********* [FF] Environments *********
std = [
    "alloc",
    "nalgebra/std",
    "serde?/std",
]

[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = false
test = true

[build-dependencies]

[dependencies]
nalgebra = { default-features = false, version = "0.33" }
num = { default-features = false, version = "0.4" }
serde = { default-features = false, optional = true, version = "1" }
strum = { default-features = false, features = ["derive"], version = "0.26" }
thiserror = { default-features = false, version = "2" }


[dev-dependencies]
anyhow = "1"
lazy_static = "1"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
